# Zuul的默认路由规则如下：http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**会被转发到serviceId对应的微服务
zuul:
  routes:
    route-a: # http://localhost:8080/a/foo
      path: /a/**
      #      service-id: video-user-provider
      #      url: http://www.baidu.com
      url: http://localhost:8080/b
    route-c: # http://localhost:8080/route/c/foo
      path: /route/c/**
      url: http://localhost:8080/c

logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: debug
